import { StyleSheet } from "react-native";

const palette = {
  black: "#050806",
  surface: "#0F1712",
  surfaceRaised: "#17211A",
  white: "#F4F7F2",
  muted: "#B7C4BA",
  line: "#294032",
  green: "#2DD36F",
  greenStrong: "#159947",
  red: "#D43D3D",
  redStrong: "#A92828",
  yellow: "#F3C969",
};

const createTheme = (mode: "light" | "dark") => {
  const isDark = mode === "dark";
  const background = isDark ? palette.black : "#FFFFFF";
  const surface = isDark ? palette.surface : "#FFFFFF";
  const surfaceRaised = isDark ? palette.surfaceRaised : "#F4FBF6";
  const text = isDark ? palette.white : "#101A13";
  const muted = isDark ? palette.muted : "#526257";
  const line = isDark ? palette.line : "#D4E2D7";
  const primary = isDark ? palette.green : palette.greenStrong;

  return StyleSheet.create({
    container: {
      flex: 1,
      width: "100%",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: background,
      paddingHorizontal: 22,
      paddingVertical: 28,
      gap: 14,
    },
    title: {
      width: "100%",
      maxWidth: 520,
      fontSize: 30,
      lineHeight: 36,
      fontWeight: "800",
      textAlign: "center",
      color: text,
      marginBottom: 4,
    },
    subtitle: {
      width: "100%",
      maxWidth: 520,
      fontSize: 16,
      lineHeight: 23,
      fontWeight: "600",
      textAlign: "center",
      color: muted,
      marginBottom: 8,
    },
    button: {
      width: "100%",
      maxWidth: 420,
      minHeight: 54,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 8,
      backgroundColor: primary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: isDark ? "#3AF27F" : primary,
    },
    buttonText: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: "800",
      color: isDark ? palette.black : palette.white,
      textAlign: "center",
    },
    status: {
      maxWidth: 420,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: "800",
      textAlign: "center",
      marginBottom: 10,
      color: muted,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: surfaceRaised,
      borderWidth: 1,
      borderColor: line,
      overflow: "hidden",
    },
    online: { color: primary },
    offline: { color: palette.red },
    themeButton: {
      position: "absolute",
      bottom: 24,
      right: 22,
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: surfaceRaised,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: line,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
    },
    themeIcon: {
      fontSize: 23,
      color: isDark ? palette.yellow : palette.black,
    },
    playersContainer: {
      width: "100%",
      maxWidth: 560,
      alignItems: "center",
      marginVertical: 12,
      gap: 10,
    },
    playersTitle: {
      width: "100%",
      maxWidth: 520,
      fontSize: 18,
      lineHeight: 25,
      fontWeight: "800",
      color: text,
      textAlign: "center",
      marginBottom: 4,
    },
    playerCard: {
      minHeight: 82,
      flex: 1,
      minWidth: 92,
      maxWidth: 160,
      backgroundColor: surface,
      borderRadius: 8,
      paddingVertical: 14,
      paddingHorizontal: 10,
      alignItems: "center",
      justifyContent: "center",
      margin: 6,
      borderWidth: 1,
      borderColor: line,
      elevation: 3,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: isDark ? 0.28 : 0.08,
      shadowRadius: 12,
    },
    avatar: {
      width: 50,
      height: 50,
      borderRadius: 25,
      marginBottom: 5,
    },
    playerName: {
      fontSize: 16,
      lineHeight: 21,
      fontWeight: "800",
      color: text,
      textAlign: "center",
    },
    row: {
      width: "100%",
      justifyContent: "center",
    },
    error: {
      width: "100%",
      maxWidth: 420,
      fontSize: 15,
      lineHeight: 21,
      color: palette.red,
      textAlign: "center",
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: isDark ? "#2A1212" : "#FCE9E9",
      borderWidth: 1,
      borderColor: isDark ? "#5A2222" : "#F3B8B8",
    },
    gameButtonContainer: {
      width: "100%",
      maxWidth: 420,
      alignItems: "center",
      marginTop: 8,
      gap: 10,
    },
    gameButton: {
      width: "100%",
      maxWidth: 420,
      minHeight: 54,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 8,
      backgroundColor: primary,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 0,
    },
    greenButton: {
      width: "100%",
      maxWidth: 420,
      minHeight: 54,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 8,
      backgroundColor: primary,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 0,
      borderWidth: 1,
      borderColor: isDark ? "#3AF27F" : primary,
    },
    redButton: {
      width: "100%",
      maxWidth: 420,
      minHeight: 54,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 8,
      backgroundColor: isDark ? palette.red : palette.redStrong,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 0,
      borderWidth: 1,
      borderColor: isDark ? "#F06161" : palette.redStrong,
    },
    gameButtonText: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: "800",
      color: palette.white,
      textAlign: "center",
    },
    gameButtonTextDark: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: "800",
      color: palette.black,
      textAlign: "center",
    },
    modalContent: {
      width: "86%",
      maxWidth: 360,
      padding: 20,
      borderRadius: 8,
      backgroundColor: surface,
      alignItems: "center",
      borderWidth: 1,
      borderColor: line,
    },
    input: {
      width: "100%",
      maxWidth: 420,
      minHeight: 54,
      fontSize: 16,
      lineHeight: 22,
      color: text,
      backgroundColor: surface,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderColor: line,
      borderWidth: 1,
      borderRadius: 8,
      alignItems: "center",
      textAlign: "center",
    },
    inputText: {
      fontSize: 16,
      fontWeight: "700",
      color: text,
    },
    smallImage: {
      width: 58,
      height: 58,
      resizeMode: "contain",
      marginBottom: 8,
    },
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: isDark ? "rgba(5, 8, 6, 0.9)" : "rgba(238, 244, 236, 0.92)",
      padding: 22,
      gap: 12,
    },
    modalTitle: {
      maxWidth: 420,
      fontSize: 26,
      lineHeight: 32,
      fontWeight: "800",
      color: text,
      textAlign: "center",
      marginBottom: 2,
    },
    modalSubtitle: {
      maxWidth: 420,
      fontSize: 17,
      lineHeight: 24,
      color: muted,
      textAlign: "center",
      marginBottom: 12,
    },
    buttonContainer: {
      width: "100%",
      maxWidth: 420,
      flexDirection: "row",
      gap: 10,
    },
    acceptButton: {
      flex: 1,
      minHeight: 50,
      backgroundColor: primary,
      padding: 12,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    denyButton: {
      flex: 1,
      minHeight: 50,
      backgroundColor: isDark ? palette.red : palette.redStrong,
      padding: 12,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    backgroundImage: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    overlay: {
      width: "88%",
      maxWidth: 460,
      backgroundColor: "rgba(5, 8, 6, 0.76)",
      padding: 24,
      borderRadius: 8,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(45, 211, 111, 0.35)",
    },
    vencedorTitle: {
      fontSize: 30,
      lineHeight: 36,
      fontWeight: "800",
      color: palette.white,
      textAlign: "center",
      marginBottom: 12,
    },
    vencedorSubtitle: {
      fontSize: 18,
      lineHeight: 25,
      color: palette.white,
      textAlign: "center",
    },
    paginationControls: {
      width: "100%",
      maxWidth: 420,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginTop: 6,
      gap: 10,
    },
    pageButton: {
      width: 48,
      height: 48,
      backgroundColor: surfaceRaised,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: line,
    },
    pageButtonText: {
      color: text,
      fontWeight: "800",
      fontSize: 18,
    },
    pageIndicator: {
      minWidth: 130,
      paddingVertical: 12,
      paddingHorizontal: 14,
      color: text,
      fontSize: 16,
      fontWeight: "800",
      textAlign: "center",
      backgroundColor: surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: line,
      overflow: "hidden",
    },
  });
};

export const lightTheme = createTheme("light");
export const darkTheme = createTheme("dark");
