import { StyleSheet } from "react-native";

export const lightTheme = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f8f8",
    paddingHorizontal: 20,
    gap: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    color: "#333",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    color: "#333",
    marginBottom: 10,
  },
  button: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: "#333",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#F1F1f1",
  },
  status: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    color: "#555",
  },
  online: { color: "green" },
  offline: { color: "red" },
  themeButton: {
    position: "absolute",
    bottom: 30,
    right: 30,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#333",
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  themeIcon: {
    fontSize: 24,
    color: "#fff",
  },
  playersContainer: {
    marginVertical: 20,
    width: "100%",
    alignItems: "center",
  },
  playersTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#333",
    marginBottom: 10,
  },
  playerCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    margin: 10,
    width: 100,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 5,
  },
  playerName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    textAlign: "center",
  },
  row: {
    justifyContent: "space-around",
  },
  error: {
    fontSize: 16,
    color: "red",
    marginTop: 10,
    textAlign: "center",
  },
  gameButtonContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 20,
  },
  gameButton: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: "#001",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  greenButton: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: "#276337",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  redButton: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: '#B71C1C',
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  gameButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  modalContent: {
    width: 250,
    padding: 20,
    borderRadius: 10,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  input: {
    fontSize: 16,
    width: "80%",
    color: "#000",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderColor: "black",
    alignItems: 'center',
    textAlign: 'center',
    borderStyle: 'solid',
  },
  inputText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
  },
  smallImage: {
    width: 50, 
    height: 50,
    resizeMode: "contain"
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.8)",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 10,
  },
  modalSubtitle: {
    fontSize: 18,
    color: "#333",
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 10,
  },
  acceptButton: {
    backgroundColor: "#4CAF50",
    padding: 10,
    borderRadius: 8,
  },
  denyButton: {
    backgroundColor: "#D32F2F",
    padding: 10,
    borderRadius: 8,
  },  
});

export const darkTheme = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.8)"
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 10,
  },
  modalSubtitle: {
    fontSize: 18,
    color: "#CCC",
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 10,
  },
  acceptButton: {
    backgroundColor: "#4CAF50",
    padding: 10,
    borderRadius: 8,
  },
  denyButton: {
    backgroundColor: "#D32F2F",
    padding: 10,
    borderRadius: 8,
  },
  smallImage: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
  input: {
    fontSize: 16,
    width: "80%",
    backgroundColor: 'white',
    color: "#000",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    alignItems: 'center',
    textAlign: 'center',
  },
  inputText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1a1a1a",
    paddingHorizontal: 20,
    gap: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    color: "#F1F1F1",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    color: "#F1F1F1",
    marginBottom: 10,
  },
  button: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: "#F1F1F1",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1a1a1a",
  },
  status: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    color: "#ccc",
  },
  online: { color: "lightgreen" },
  offline: { color: "tomato" },
  themeButton: {
    position: "absolute",
    bottom: 30,
    right: 30,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#F1F1F1",
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  themeIcon: {
    fontSize: 24,
    color: "yellow",
  },
  playersContainer: {
    marginVertical: 20,
    width: "100%",
    alignItems: "center",
  },
  playersTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: "#F1F1F1",
    marginBottom: 10,
  },
  playerCard: {
    backgroundColor: "#333",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    margin: 10,
    width: 100,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 5,
  },
  playerName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#F1F1F1",
    textAlign: "center",
  },
  row: {
    justifyContent: "space-around",
  },
  error: {
    fontSize: 16,
    color: "tomato",
    marginTop: 10,
    textAlign: "center",
  },
  gameButtonContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 20,
  },
  gameButton: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: "#F1F1F1",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  greenButton: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: "#276337",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  redButton: {
    width: "80%",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    backgroundColor: '#B71C1C',
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  gameButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  gameButtonTextDark: {
    fontSize: 16,
    fontWeight: "600",
    color: "#001",
  },
  modalContent: {
    width: 250,
    padding: 20,
    borderRadius: 10,
    backgroundColor: "#001",
    alignItems: "center",
  },
});
